services:
  - type: web
    name: gestionale-magazzino
    runtime: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SESSION_COOKIE_SECURE
        value: "1"
